name: Build MetaDataDebugTools

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-14]
        qt_version: [6.7.3]
        include:
          - os: ubuntu-22.04
            qt_target: linux
            qt_arch: desktop
            qt_compiler: gcc_64
            qt_modules: qtbase qttools
          - os: windows-2022
            qt_target: windows
            qt_arch: desktop
            qt_compiler: win64_msvc2022
            qt_modules: qtbase qttools
          - os: macos-14
            qt_target: mac
            qt_arch: desktop
            qt_compiler: clang_64
            qt_modules: qtbase qttools

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install aqt
      run: pip install aqtinstall

    - name: Install Qt ${{ matrix.qt_version }}
      run: |
        aqt install-qt ${{ matrix.qt_target }} ${{ matrix.qt_arch }} ${{ matrix.qt_version }} ${{ matrix.qt_compiler }} -m ${{ matrix.qt_modules }}
        echo "QT_DIR=$PWD/Qt/${{ matrix.qt_version }}/${{ matrix.qt_compiler }}" >> $GITHUB_ENV

    - name: Install system dependencies (Linux)
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev build-essential

    - name: Install system dependencies (macOS)
      if: matrix.os == 'macos-14'
      run: |
        brew install pkg-config

    - name: Configure project
      shell: cmd
      if: matrix.os == 'windows-2022'
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        "%QT_DIR%\bin\qmake" MetaDataDebugTools.pro -spec win32-msvc

    - name: Configure project (Unix)
      if: matrix.os != 'windows-2022'
      run: |
        ${{ env.QT_DIR }}/bin/qmake MetaDataDebugTools.pro

    - name: Build project (Linux/macOS)
      if: matrix.os != 'windows-2022'
      run: make -j4

    - name: Build project (Windows)
      shell: cmd
      if: matrix.os == 'windows-2022'
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        nmake
