name: Build MetaDataDebugTools (Windows EXE)

on:
  push:
    branches: [ master ]
    paths: 
      - 'DevTools/MetaDataDebugTools/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'DevTools/MetaDataDebugTools/**'
  workflow_dispatch:

jobs:
  build-windows-exe:
    runs-on: windows-latest
    strategy:
      matrix:
        qt-version: ['6.7.3']
        architecture: [x86_64]  # 也可添加 win32_mingw

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Qt ${{ matrix.qt-version }} (Windows)
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt-version }}
        host: windows
        target: desktop
        arch: ${{ matrix.architecture }}
        modules: qtbase qtsvg qt5compat
        install-deps: true
        cached: true
        setup-python: false

    - name: Add Qt to PATH
      shell: pwsh
      run: |
        $qtPath = "$env:QT_PATH/bin"
        Write-Output "Adding Qt to PATH: $qtPath"
        Add-Content $env:GITHUB_PATH "$qtPath"

    - name: Configure project
      working-directory: ./DevTools/MetaDataDebugTools
      shell: cmd
      run: |
        qmake MetaDataDebugTools.pro CONFIG+=release -spec win32-msvc
        if errorlevel 1 exit 1

    - name: Build project
      working-directory: ./DevTools/MetaDataDebugTools
      shell: cmd
      run: |
        jom.exe || nmake  # jom 更快，回退到 nmake
        if errorlevel 1 exit 1

    - name: Bundle dependencies with windeployqt
      working-directory: ./DevTools/MetaDataDebugTools/release
      shell: pwsh
      run: |
        windeployqt --compiler-runtime --no-translations --no-opengl-sw MetaDataDebugTools.exe
        Write-Output "Deployed dependencies:"
        dir

    - name: Create ZIP package
      working-directory: ./DevTools/MetaDataDebugTools/release
      shell: pwsh
      run: |
        $version = (Get-Date -Format "yyyyMMdd")
        $zipName = "MetaDataDebugTools_Qt${{ matrix.qt-version }}_${{ matrix.architecture }}_$version.zip"
        Compress-Archive -Path * -DestinationPath $zipName
        Move-Item $zipName ..\..\
        Write-Output "Created package: $zipName"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MetaDataDebugTools-Windows-Qt${{ matrix.qt-version }}
        path: |
          ./DevTools/MetaDataDebugTools/release/MetaDataDebugTools.exe
          ./DevTools/MetaDataDebugTools/*.zip
        retention-days: 7
